language: node_js

cache: yarn

node_js:
  - 8
  - 10

before_install:
  - npm i -g yarn

script:
  - yarn test

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/adea2c63a919e9b1c7a1
    on_success: change
    on_failure: always
    on_start: never

env:
  global:
    - secure: NvyHrFnxSvZxzARD1C0Vb4a4OP2hkIYnASyENkxfJbjoOcQixDr+13boWw/w2mlULJmdsvRxDYsiSPvk8Wt0zOnMVgF+M5EiDMGtkhiaFRXzWmXjQ3Hh+Wh14YBKnv/fdlZx1XMCcRuiFKg/d1e/x2B/kJD++U0HuY97TQSSQ1cX8sCfNl1wr/bNUvsmxNfOXNYYrpr72jNVkIa+xXAiqO/yY69N99N+OdpZTLUfXOug0RX7ga9WB+iwAb1IMaHmLIns5TLynLilmm8Lgu28gHdWNQMqD7Gqy7M1SKYnY7yRfB1rJ5ulwstpZU24kiUyaRMNMIilN5ikduAbsnHriJqEUCXvcXJbQRuKL+RLoAw6feMDPSCiXZNtUJ8iJn1PjbmkPYb6zyF7IwQoP6r+oZ378ZtYQNLEln8IF1ww9Lv/hkp+8JRqzdOogzY8mg84iKiJTStaNuWwcQDpsG/WX62ewaq+5lod5Iv2n33aCcC2e+uWjXbkeocDnSU19IYLogl57Ph1pcNG7jIJQzU9KFPEg7urlimp0GWNOYJ1rKNDl4nvrnddAnD5cViPKAZte7WCbO+1kZ8TxV+34YUQ47Q7gfb/QgRXnyfsvmQHth1nYDLSxk1UNolu6BLg+kfzyPEmYd1I4E+JOEIv2G5k26LgCp6gi1SHVJVN2EUZmP4=
    - secure: n8lhPXGvTjvwOdA7WqczupcE7Ul2wbTnNIqGE3Ui3aowbxNd1DuFd2F3fmx/2525us6WC2MkejTSu/32nR+GzpX4nr3j+E/WcntjGUiiZZsDK4jMj3IFSPzVfG45/rYzSR0dbwGXt4WE6uiv3tUMg+YAL7GIcyt+Sb2V3hUxkr+UjzJw/lKZlK+ihj5NsntO95NpK7f7yPITzModFBpotCzMabFHmVC4UWt8J8uMvjtq7mQvmYWrdHD3SE5nCovWYB9n9AEEQql5CgySPpyEPR1QgOxofR/KnRidTreuYuIVIuPXTb9DrjRPZRXmDKbQe0ridWsgO+N3ijC/TKl167JsnGMENWIUepCQkNS0PtUFekrAciTeicMt3r2pQP65HUdI7x/BYTVTV0iJXJx21py1NYuyv2bfPNmg6wQikK+J9TVOIAkIc23bg8WrU/u2FOPcikhNjEr0PMLz9EjfLPZDUbZDVs7SS1Ti1BsbtETB+u75pqCmfSLztC8ctvXwTqvYvA4lHJxi/iCI0kaKIbHtS5NC3PI4yl5OwF8yBPL7rH9bnQTY3H9kApzio5KrkWfTFP/3oGEY5qjEoriX3wzLU2mG2H4zdRYxB5u67T1TdoT3Mr7LF9vo28CUrgIznQqiN6BZ7+/Ngncmwb2N18L4UJ6IcuKETbFO5jPsWLM=
    - export GIT_AUTHOR_NAME="ServerlizeBot"
    - export GIT_AUTHOR_EMAIL="hello@serverlize.net"
    - export GIT_COMMITTER_NAME="Serverlize Bot"
    - export GIT_COMMITTER_EMAIL="hello@serverlize.net"

jobs:
  include:
    - stage: coverage
      if: type != pull_request
      after_success:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - for f in packages/*; do
            if [ -d $f ]; then
              echo $f;
              ./cc-test-reporter format-coverage -t lcov -o coverage/coverage.${f//\//-}.json $f/coverage/lcov.info;
            fi
          done;
        - ./cc-test-reporter sum-coverage -o coverage/coverage.total.json coverage/coverage.*.json;
        - ./cc-test-reporter upload-coverage -i coverage/coverage.total.json;
    - stage: release
      if: branch = master
      after_success:
        - yarn release
