language: node_js

node_js:
  - 10
  - 8
  - 6

before_install:
  - npm i -g yarn
  - yarn global add greenkeeper-lockfile@2

before_script:
  - greenkeeper-lockfile-update
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

script:
  - yarn precommit

after_script:
  - greenkeeper-lockfile-upload

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      for f in packages/*; do
        if [ -d $f ]; then
          echo $f;
          ./cc-test-reporter format-coverage -t lcov -o coverage/coverage.${f//\//-}.json $f/coverage/lcov.info;
        fi
      done;
      ./cc-test-reporter sum-coverage -o coverage/coverage.total.json coverage/coverage.*.json;
      ./cc-test-reporter upload-coverage -i coverage/coverage.total.json;
    fi

matrix:
  allow_failures:
    - node_js: 10

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/adea2c63a919e9b1c7a1
    on_success: change
    on_failure: always
    on_start: never

env:
